version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.1"
    container_name: "traefik"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --log.filePath=/var/log/traefik.log
      - --accesslog=true
      - --accesslog.bufferingsize=100
      - --accesslog.filePath=/var/log/access.log
      - --entryPoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${SSL_MAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-secured.rule=Host(`dashboard.${DOMAIN}`)
      - traefik.http.routers.traefik-secured.entrypoints=websecure
      - traefik.http.routers.traefik-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-secured.service=api@internal
      - traefik.http.routers.traefik-secured.middlewares=basic-auth@docker
      - traefik.http.middlewares.web-compress.compress=true
      - traefik.http.middlewares.web-ratelimit.ratelimit.average=600
      - traefik.http.middlewares.api-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.basic-auth.basicauth.users=${BASIC_AUTH}
      - traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https
    volumes:
      - ./log:/var/log
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    image: "elecweb/react-with-docker"
    container_name: "frontend"
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.middlewares=redirecthttps
      - traefik.http.routers.frontend-secured.middlewares=web-compress@docker,web-ratelimit@docker
      - traefik.http.routers.frontend-secured.entrypoints=websecure
      - traefik.http.routers.frontend-secured.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend-secured.service=frontend-service
      - traefik.http.routers.frontend-secured.tls.certresolver=letsencrypt
      - traefik.http.services.frontend-service.loadbalancer.server.port=3000

  backend:
    image: "wimkung/hapi-with-docker"
    container_name: "backend"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.middlewares=redirecthttps
      - traefik.http.routers.backend-secured.middlewares=api-ratelimit@docker
      - traefik.http.routers.backend-secured.entrypoints=websecure
      - traefik.http.routers.backend-secured.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend-secured.service=backend-service
      - traefik.http.routers.backend-secured.tls.certresolver=letsencrypt
      - traefik.http.services.backend-service.loadbalancer.server.port=8000